### ISSUE TITLE
Solutions in Golang

### ISSUE THREAD

**Issue by abhishekunotech** [nerdyninja/gstarena-solutions#5]

**Comment by nerdyninja** [comment]
Solutions for _Golang_ updated in Branch: _**go-lang**_.

PS: You too, can provide solutions for Java or Python!

**Comment by abhishekunotech** [comment]
Will do a PR for Python, since Vishal is doing it for Java AFAIK

**Comment by nerdyninja** [comment]
Yeah cool 👍 Thanks 😄
